@startuml Sequence Diagram
scale 1
' skinparam style strictuml

' Create a System Sequence Diagram for the success scenario of Use Case Processing Annotations and identify System Operations.
hide empty members

actor SystemAdmin as "System Administrator"

participant System

SystemAdmin -> System: startSession()
|||
SystemAdmin -> System: createLocation(x, y)
SystemAdmin <-- System: newLocation
|||
SystemAdmin -> System: createDescription(type, name)
SystemAdmin <-- System: newDescription
|||
SystemAdmin -> System: addAnnotation(location, description)
SystemAdmin <-- System: confirmation
|||
SystemAdmin -> System: endSession()
@enduml