@startuml Communication Model (addAnnotation())
scale 1
skinparam style strictuml
' Disables the icons on the class attributes (colored icons)
' skinparam classAttributeIconSize 0 

' Create a UML Interaction Diagram (either a Sequence Diagram or a Communications Diagram for operation addAnnotation(..)
hide empty members

object ":Console" as Console
object ":Map" as Map
object ":Annotation" as Annotation

Actor --> Console: addAnnotation(location, description)

Console -> Map: 1.1: createId(location, description)
Map --> Map: 1.2: checkUniqueId(id)

Map --> Annotation: 1.3: [id is unique] create(id)
@enduml